apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: ubuntu:22.04
    name: pod1
    command: ["/bin/bash", "-c"]
    args: ["
    while true; do { date +\"%T.%3N\"; hostname; stat /workdir/share_point/example.txt; } >> pod1.log 2>&1; sleep 1; done && 
    tail -f /dev/null"]
    volumeMounts:
      - name: persistent-storage
        mountPath: /workdir/share_point
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
